<?php

use Illuminate\Database\Seeder;
use MXU\Member\Models\CreditRules;

class MemberCreditRulesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->member_credit_rules();
    }

    public function member_credit_rules()
    {
        $rules = [
            [
                'id'             => 1,
                'rule_name'      => '注册',
                'operation'      => 'register',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 1,
                'rule_level'     => 0,
                'rule_type'      => 4,
                'rule_times'     => 0,
                'rule_num'       => 1,
                'exp_points'     => 0,
                'credits'        => 1000,
                'rule_detail'    => '注册之后的初始经验：积分+1000。',
                'order_id'       => 1,
                'rule_introduce' => '会员注册之后的初始经验',
                'app_status'     => 1,
            ],
            [
                'id'             => 2,
                'rule_name'      => '第一次使用app',
                'operation'      => 'open_client',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 1,
                'rule_level'     => 0,
                'rule_type'      => 4,
                'rule_times'     => 0,
                'rule_num'       => 1,
                'exp_points'     => 0,
                'credits'        => 500,
                'rule_detail'    => '第一次登陆APP：积分+500。',
                'order_id'       => 2,
                'rule_introduce' => '会员第一次登陆APP',
                'app_status'     => 1,
            ],
            [
                'id'             => 3,
                'rule_name'      => '上传头像',
                'operation'      => 'upload_avatar',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 1,
                'rule_level'     => 0,
                'rule_type'      => 4,
                'rule_times'     => 0,
                'rule_num'       => 1,
                'exp_points'     => 0,
                'credits'        => 100,
                'rule_detail'    => '第一次上传头像：积分+100。',
                'order_id'       => 3,
                'rule_introduce' => '会员第一次上传头像',
                'app_status'     => 1,
            ],
            [
                'id'             => 4,
                'rule_name'      => '登录',
                'operation'      => 'login',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 1,
                'rule_level'     => 0,
                'rule_type'      => 1,
                'rule_times'     => 0,
                'rule_num'       => 1,
                'exp_points'     => 10,
                'credits'        => 50,
                'rule_detail'    => '在网站或APP登录：经验+10，积分+50。',
                'order_id'       => 4,
                'rule_introduce' => '会员在网站或APP登录',
                'app_status'     => 1,
            ],
            [
                'id'             => 5,
                'rule_name'      => '发表评论',
                'operation'      => 'comment',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 1,
                'rule_level'     => 0,
                'rule_type'      => 1,
                'rule_times'     => 0,
                'rule_num'       => 3,
                'exp_points'     => 5,
                'credits'        => 50,
                'rule_detail'    => '评论新闻内容：经验+5，积分+500。',
                'order_id'       => 5,
                'rule_introduce' => '会员评论新闻内容',
                'app_status'     => 1,
            ],
            [
                'id'             => 6,
                'rule_name'      => '发布评论并通过审核',
                'operation'      => 'comment_pass',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 0,
                'rule_level'     => 0,
                'rule_type'      => 1,
                'rule_times'     => 0,
                'rule_num'       => 3,
                'exp_points'     => 5,
                'credits'        => 50,
                'rule_detail'    => '评论新闻内容并通过后台审核：经验+5，积分+50。',
                'order_id'       => 6,
                'rule_introduce' => '会员评论新闻内容并通过后台审核',
                'app_status'     => 1,
            ],
            [
                'id'             => 7,
                'rule_name'      => '评论删除',
                'operation'      => 'comment_delete',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 1,
                'rule_level'     => 0,
                'rule_type'      => 4,
                'rule_times'     => 0,
                'rule_num'       => 0,
                'exp_points'     => -5,
                'credits'        => -50,
                'rule_detail'    => '评论新闻内容被删除：经验-5，积分-50。',
                'order_id'       => 7,
                'rule_introduce' => '会员评论新闻内容被删除',
                'app_status'     => 0,
            ],
            [
                'id'             => 8,
                'rule_name'      => '观看直播',
                'operation'      => 'live',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 1,
                'rule_level'     => 0,
                'rule_type'      => 1,
                'rule_times'     => 0,
                'rule_num'       => 1,
                'exp_points'     => 0,
                'credits'        => 100,
                'rule_detail'    => '观看直播内容：积分+100。',
                'order_id'       => 8,
                'rule_introduce' => '会员观看直播内容',
                'app_status'     => 1,
            ],
            [
                'id'             => 9,
                'rule_name'      => '发布报料',
                'operation'      => 'contribute',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 1,
                'rule_level'     => 0,
                'rule_type'      => 1,
                'rule_times'     => 0,
                'rule_num'       => 1,
                'exp_points'     => 5,
                'credits'        => 100,
                'rule_detail'    => '发布报料内容：经验+5，积分+100。',
                'order_id'       => 9,
                'rule_introduce' => '会员发布报料内容',
                'app_status'     => 1,
            ],
            [
                'id'             => 10,
                'rule_name'      => '发布报料并通过审核',
                'operation'      => 'contribute_pass',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 0,
                'rule_level'     => 0,
                'rule_type'      => 1,
                'rule_times'     => 0,
                'rule_num'       => 1,
                'exp_points'     => 5,
                'credits'        => 100,
                'rule_detail'    => '发布报料内容并通过后台审核：经验+5，积分+100。',
                'order_id'       => 10,
                'rule_introduce' => '会员发布报料内容并通过后台审核',
                'app_status'     => 1,
            ],
            [
                'id'             => 11,
                'rule_name'      => '报料删除',
                'operation'      => 'contribute_delete',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 1,
                'rule_level'     => 0,
                'rule_type'      => 4,
                'rule_times'     => 0,
                'rule_num'       => 0,
                'exp_points'     => -5,
                'credits'        => -100,
                'rule_detail'    => '报料内容被删除：经验-5，积分-100。',
                'order_id'       => 11,
                'rule_introduce' => '会员报料内容被删除',
                'app_status'     => 0,
            ],
            [
                'id'             => 12,
                'rule_name'      => '分享',
                'operation'      => 'share',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 1,
                'rule_level'     => 0,
                'rule_type'      => 1,
                'rule_times'     => 0,
                'rule_num'       => 1,
                'exp_points'     => 5,
                'credits'        => 100,
                'rule_detail'    => '通过APP分享按钮分享内容：经验+5，积分+100。',
                'order_id'       => 12,
                'rule_introduce' => '会员通过APP分享按钮分享内容',
                'app_status'     => 1,
            ],
            [
                'id'             => 13,
                'rule_name'      => '投票',
                'operation'      => 'vote',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 1,
                'rule_level'     => 0,
                'rule_type'      => 1,
                'rule_times'     => 0,
                'rule_num'       => 1,
                'exp_points'     => 5,
                'credits'        => 0,
                'rule_detail'    => '参与投票：经验+5。',
                'order_id'       => 13,
                'rule_introduce' => '会员参与投票',
                'app_status'     => 1,
            ],
            [
                'id'             => 14,
                'rule_name'      => '发布路况',
                'operation'      => 'road_create',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 1,
                'rule_level'     => 0,
                'rule_type'      => 1,
                'rule_times'     => 0,
                'rule_num'       => 2,
                'exp_points'     => 5,
                'credits'        => 0,
                'rule_detail'    => '客户端发布路况信息：经验+5。',
                'order_id'       => 14,
                'rule_introduce' => '会员在客户端发布路况信息',
                'app_status'     => 1,
            ],
            [
                'id'             => 15,
                'rule_name'      => '发布路况并通过审核',
                'operation'      => 'road_pass',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 0,
                'rule_level'     => 0,
                'rule_type'      => 1,
                'rule_times'     => 0,
                'rule_num'       => 2,
                'exp_points'     => 2,
                'credits'        => 0,
                'rule_detail'    => '客户端发布路况信息并通过后台审核：经验+2。',
                'order_id'       => 15,
                'rule_introduce' => '会员在客户端发布路况信息并通过后台审核',
                'app_status'     => 1,
            ],
            [
                'id'             => 16,
                'rule_name'      => '路况删除',
                'operation'      => 'road_delete',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 1,
                'rule_level'     => 0,
                'rule_type'      => 4,
                'rule_times'     => 0,
                'rule_num'       => 0,
                'exp_points'     => -2,
                'credits'        => 0,
                'rule_detail'    => '发布路况信息被删除：经验-2。',
                'order_id'       => 16,
                'rule_introduce' => '会员在发布路况信息被删除',
                'app_status'     => 0,
            ],
            [
                'id'             => 17,
                'rule_name'      => '社区发帖',
                'operation'      => 'bbs_post',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 1,
                'rule_level'     => 0,
                'rule_type'      => 1,
                'rule_times'     => 0,
                'rule_num'       => 2,
                'exp_points'     => 5,
                'credits'        => 0,
                'rule_detail'    => '社区发帖：经验+5。',
                'order_id'       => 17,
                'rule_introduce' => '会员在社区发帖',
                'app_status'     => 1,
            ],
            [
                'id'             => 18,
                'rule_name'      => '社区发帖并通过审核',
                'operation'      => 'bbs_post_audit',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 1,
                'rule_level'     => 0,
                'rule_type'      => 1,
                'rule_times'     => 0,
                'rule_num'       => 2,
                'exp_points'     => 5,
                'credits'        => 0,
                'rule_detail'    => '社区发帖通过审核：经验+5。',
                'order_id'       => 18,
                'rule_introduce' => '会员在社区发帖',
                'app_status'     => 1,
            ],
            [
                'id'             => 19,
                'rule_name'      => '帖子被删除',
                'operation'      => 'bbs_delete',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 1,
                'rule_level'     => 0,
                'rule_type'      => 4,
                'rule_times'     => 0,
                'rule_num'       => 0,
                'exp_points'     => -5,
                'credits'        => 0,
                'rule_detail'    => '社区发帖被删除：经验-5，积分-0。',
                'order_id'       => 19,
                'rule_introduce' => '会员在社区发帖被删除',
                'app_status'     => 0,
            ],
            [
                'id'             => 20,
                'rule_name'      => '社区跟帖',
                'operation'      => 'bbs_reply',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 1,
                'rule_level'     => 0,
                'rule_type'      => 1,
                'rule_times'     => 0,
                'rule_num'       => 10,
                'exp_points'     => 2,
                'credits'        => 0,
                'rule_detail'    => '社区中回帖：经验+2。',
                'order_id'       => 19,
                'rule_introduce' => '会员在社区中回帖',
                'app_status'     => 1,
            ],
            [
                'id'             => 21,
                'rule_name'      => '社区跟帖并通过审核',
                'operation'      => 'bbs_reply_audit',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 1,
                'rule_level'     => 0,
                'rule_type'      => 1,
                'rule_times'     => 0,
                'rule_num'       => 10,
                'exp_points'     => 2,
                'credits'        => 0,
                'rule_detail'    => '社区中回帖通过审核：经验+2。',
                'order_id'       => 21,
                'rule_introduce' => '会员在社区中回帖',
                'app_status'     => 1,
            ],
            [
                'id'             => 22,
                'rule_name'      => '跟帖被删除',
                'operation'      => 'bbs_reply_delete',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 1,
                'rule_level'     => 0,
                'rule_type'      => 4,
                'rule_times'     => 0,
                'rule_num'       => 0,
                'exp_points'     => -2,
                'credits'        => 0,
                'rule_detail'    => '社区跟帖被删除：经验-2。',
                'order_id'       => 22,
                'rule_introduce' => '会员在社区跟帖被删除',
                'app_status'     => 0,
            ],
            [
                'id'             => 23,
                'rule_name'      => '帖子被置为热门',
                'operation'      => 'bbs_post_hot',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 1,
                'rule_level'     => 0,
                'rule_type'      => 4,
                'rule_times'     => 0,
                'rule_num'       => 0,
                'exp_points'     => 30,
                'credits'        => 0,
                'rule_detail'    => '社区发帖被管理员置为热门：经验+30。',
                'order_id'       => 23,
                'rule_introduce' => '会员在社区发帖被管理员置为热门',
                'app_status'     => 1,
            ],
            [
                'id'             => 24,
                'rule_name'      => '帖子被置为精华',
                'operation'      => 'bbs_post_essence',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 1,
                'rule_level'     => 0,
                'rule_type'      => 4,
                'rule_times'     => 0,
                'rule_num'       => 0,
                'exp_points'     => 50,
                'credits'        => 0,
                'rule_detail'    => '社区发帖被管理员置为精华：经验+50。',
                'order_id'       => 24,
                'rule_introduce' => '会员在社区发帖被管理员置为精华',
                'app_status'     => 1,
            ],
            [
                'id'             => 25,
                'rule_name'      => '帖子被置顶',
                'operation'      => 'bbs_post_top',
                'is_system'      => 1,
                'is_custom'      => 0,
                'status'         => 1,
                'rule_level'     => 0,
                'rule_type'      => 4,
                'rule_times'     => 0,
                'rule_num'       => 0,
                'exp_points'     => 30,
                'credits'        => 0,
                'rule_detail'    => '社区发帖被管理员置顶：经验+30。',
                'order_id'       => 25,
                'rule_introduce' => '会员在社区发帖被管理员置顶',
                'app_status'     => 1,
            ],
        ];

        foreach ($rules as $rule) {
            if (!CreditRules::where('id', $rule['id'])->count()) {
                CreditRules::create($rule);
            }
        }
    }
}
